name: Deploy Nginx Blue-Green

on:
  push:
    branches:
      - main

jobs:
  validate-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: sudo apt-get update && sudo apt-get install -y gettext-base

      - name: Validar proceso de Conmutación (Verde)
        run: |
          # 1. Definir variables (Simulando el script)
          export APP_TARGET_IP="192.168.1.20"
          export APP_TARGET_PORT="8080"
          export DEPLOYMENT_COLOR="Verde"
          
          echo "Probando generación de configuración para entorno: $DEPLOYMENT_COLOR"
          
          # 2. Ejecutar envsubst con tu plantilla real
          envsubst '${APP_TARGET_IP} ${APP_TARGET_PORT} ${DEPLOYMENT_COLOR}' < nginx.conf.template > default.conf
          
          # 3. Mostrar el resultado en los logs de GitHub para evidencia
          echo "--- ARCHIVO GENERADO ---"
          cat default.conf
          
          # 4. Verificación de seguridad: ¿Está el color correcto?
          if grep -q "X-Deployment-Color Verde" default.conf; then
            echo "¡Validación exitosa! El archivo se generó correctamente con el color Verde."
          else
            echo "Error: El color no coincide."
            exit 1
          fi
