name: Deploy Nginx Blue-Green

on:
  push:
    branches:
      - main

jobs:
  validate-nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simular Despliegue y Validar Variables
        run: |
          # 1. Definir las variables de entorno
          export APP_TARGET_IP="192.168.1.20"
          export APP_TARGET_PORT="8080"
          export DEPLOYMENT_COLOR="Verde"
          
          echo "Ejecutando validación para el entorno: $DEPLOYMENT_COLOR"
          
          # 2. Reemplazar variables en la plantilla
          # Esto es exactamente lo que hace tu script switch.sh
          envsubst '${APP_TARGET_IP} ${APP_TARGET_PORT} ${DEPLOYMENT_COLOR}' < nginx.conf.template > default.conf
          
          # 3. Mostrar el archivo final en el log como evidencia
          echo "--- Archivo Nginx Generado ---"
          cat default.conf
          
          # 4. Comprobación final
          if grep -q "Verde" default.conf; then
            echo "¡Éxito! La automatización funciona correctamente."
          else
            echo "Error en las variables."
            exit 1
          fi
